### ISSUE TITLE
Error when creating the EMM database

### ISSUE THREAD

**Issue by kishorejake** [wso2-attic/product-emm-1.1.0#17]
This happened when i changed the default h2 to mysql db, I'm in Linux and i ran wso2server.sh -Dsetup after gone through the documentation

The full error is :

Error when creating the EMM database
java.lang.Exception: Error when creating the EMM database
at org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:74)
at org.wso2.mobile.utils.internal.EMMUtilsServiceComponent.activate(EMMUtilsServiceComponent.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.NullPointerException
at org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQL(EMMDBInitializer.java:277)
at org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQLScript(EMMDBInitializer.java:121)
at org.wso2.mobile.utils.persistence.EMMDBInitializer.createEMMDatabase(EMMDBInitializer.java:52)
at org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:70)
... 16 more

**Comment by kenneththorman** [comment]
I have this error as well

**Comment by kasundananjaya** [comment]
Hi,

Did you add the MysqlJDBC driver? If not, please add it to repository/components/lib as described in our documentation [1].

[1] - https://docs.wso2.com/display/EMM110/Setting+up+MySQL

Thanks

**Comment by kenneththorman** [comment]
Hi Kasun

Yes I did add it and I created a new issue located at https://wso2.org/jira/browse/EMM-816

But in short

Environment: Centos 6.7, JDK1.7.80 64-bit (Official Oracle), mysql-community-server.x86_64 5.6.27-2.el6, mysql-connector-java-5.1.36


Official release 1.1.0 downloaded and built from sources on Centos 6.7 with a mysql 5.6 installed and JDK 1.7.80
Steps to reproduce
Just run ./wso2server.sh -Dsetup
Error in output
[2015-10-15 07:19:05,287] ERROR
{org.wso2.mobile.utils.internal.EMMUtilsServiceComponent}
Error when creating the EMM database
java.lang.Exception: Error when creating the EMM database
at org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:74)
at org.wso2.mobile.utils.internal.EMMUtilsServiceComponent.activate(EMMUtilsServiceComponent.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.NullPointerException
at org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQL(EMMDBInitializer.java:277)
at org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQLScript(EMMDBInitializer.java:121)
at org.wso2.mobile.utils.persistence.EMMDBInitializer.createEMMDatabase(EMMDBInitializer.java:52)
at org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:70)
... 16 more



Seems to be caused by this lacking the mysql database server type? I have not debugged this, just investigated and found this sources, maybe mysql is covered by the "oracle" type?
But that hardly makes sense since they are not at all compatible.

https://github.com/wso2/product-emm/blob/5cdc4168cf784671ad3f70ebcf05c6c4a621b8ce/modules/components/emm-utils/src/main/java/org/wso2/mobile/utils/persistence/EMMDBInitializer.java#L77


master-datasources.xml:
...
<datasource>
<name>WSO2_EMM_DB</name>
<description>The datasource used for EMM</description>
<jndiConfig>
<name>jdbc/WSO2EMMDB</name>
</jndiConfig>
<definition type="RDBMS">
<configuration>
<url>jdbc:mysql://localhost:3306/WSO2EMM_DB</url>
<username>XXXXXXXXX</username>
<password>XXXXXXXXX</password>
<driverClassName>com.mysql.jdbc.Driver</driverClassName>
<maxActive>50</maxActive>
<maxWait>60000</maxWait>
<testOnBorrow>true</testOnBorrow>
<validationQuery>SELECT 1</validationQuery>
<validationInterval>30000</validationInterval>
</configuration>
</definition>
</datasource>
....

**Comment by kasundananjaya** [comment]
Hi Kenneth,

Are you sure you have set proper permissions? And also make sure you follow
the steps in [1] properly.

[1] - https://docs.wso2.com/display/EMM110/Setting+up+MySQL

Thanks

On Tue, Oct 20, 2015 at 5:05 PM, Kenneth Thorman <notifications@github.com>
wrote:

> Hi Kasun
>
> Yes I did add it and I created a new issue located at
> https://wso2.org/jira/browse/EMM-816
>
> But in short
>
> Environment: Centos 6.7, JDK1.7.80 64-bit (Official Oracle),
> mysql-community-server.x86_64 5.6.27-2.el6, mysql-connector-java-5.1.36
>
> Official release 1.1.0 downloaded and built from sources on Centos 6.7
> with a mysql 5.6 installed and JDK 1.7.80
> Steps to reproduce
> Just run ./wso2server.sh -Dsetup
> Error in output
> [2015-10-15 07:19:05,287] ERROR
> {org.wso2.mobile.utils.internal.EMMUtilsServiceComponent}
> Error when creating the EMM database
> java.lang.Exception: Error when creating the EMM database
> at
> org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:74)
> at
> org.wso2.mobile.utils.internal.EMMUtilsServiceComponent.activate(EMMUtilsServiceComponent.java:46)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at
> org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
> at
> org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
> at
> org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
> at
> org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
> at
> org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
> at
> org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
> at
> org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
> at
> org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
> at
> org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
> at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
> at
> org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
> Caused by: java.lang.NullPointerException
> at
> org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQL(EMMDBInitializer.java:277)
> at
> org.wso2.mobile.utils.persistence.EMMDBInitializer.executeSQLScript(EMMDBInitializer.java:121)
> at
> org.wso2.mobile.utils.persistence.EMMDBInitializer.createEMMDatabase(EMMDBInitializer.java:52)
> at
> org.wso2.mobile.utils.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:70)
> ... 16 more
>
> Seems to be caused by this lacking the mysql database server type? I have
> not debugged this, just investigated and found this sources, maybe mysql is
> covered by the "oracle" type?
> But that hardly makes sense since they are not at all compatible.
>
>
> https://github.com/wso2/product-emm/blob/5cdc4168cf784671ad3f70ebcf05c6c4a621b8ce/modules/components/emm-utils/src/main/java/org/wso2/mobile/utils/persistence/EMMDBInitializer.java#L77
>
> master-datasources.xml:
> ...
>
> WSO2_EMM_DB
> The datasource used for EMM
>
> jdbc/WSO2EMMDB
>
>
>
> jdbc:mysql://localhost:3306/WSO2EMM_DB
> XXXXXXXXX
> XXXXXXXXX
> com.mysql.jdbc.Driver
> 50
> 60000
> true
> SELECT 1
> 30000
>
>
>
> ....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wso2/product-emm/issues/17#issuecomment-149534264>.
>



-- 
Kasun Dananjaya Delgolla

Software Engineer
WSO2 Inc.; http://wso2.com
lean.enterprise.middleware
Tel:  +94 11 214 5345
Fax: +94 11 2145300
Mob: + 94 771 771 015
Blog: http://kddcodingparadise.blogspot.com
Linkedin: *http://lk.linkedin.com/in/kasundananjaya
<http://lk.linkedin.com/in/kasundananjaya>*
